### ISSUE TITLE
Did you test what aws-sdk returns? 

### ISSUE THREAD

**Issue by JordiSapesPlanas** [Oscars35/AWS-Practices#1]
https://github.com/Oscars35/AWS-Practices/blob/9d7e57bbd69187410d148d66099f02a6c23846e0/practices/practice2/get.ts#L9

Hola Oscar, estas segur que retornes el item que esta a base de dades nomes?

**Comment by Oscars35** [comment]
Al principi printava el que retornava i si no vaig errat retornava tota la tupla.
Ara mateix ho torno a revisar.
Gràcies.

**Comment by Oscars35** [comment]
Acabo de revisar la documentació. El mètode get retorna el conjunt de items de la clau passada però, com és un await ho retorna amb l'objecte Promise no?

**Comment by JordiSapesPlanas** [comment]
Si fessis el següent a la variable response tindries la promesa guardada. 
```
const response = client.get(...).promise()
```

El fet de posar el await el que fa el codi e esperar que la promesa s'hagi executat. T'animo a que ho provis i imprimeixis la resposta per veureu millor. 

Respecte el tema de la resposta de la SDK de amazon et retorna mes coses a part de l'Item. Et recomano que també ho imprimeixis per pantalla i així ho veuras.

**Comment by Oscars35** [comment]
Lo del await ho entenc perfectament, si treïem el await tant sols printa que el retorn és una Promise ja que aquesta encara no ha acabat.
En canvi, lo de la resposta SDK, després de fer varies proves, observo que si printo tot el return, retorna com un "JSON" ón l'apartat ITEM és la tupla, en canvi, si retorno tant sols "return client.get(...).promise().Item", ja si que solament retorna la tupla. És això?

**Comment by Oscars35** [comment]
> Lo del await ho entenc perfectament, si treïem el await tant sols printa que el retorn és una Promise ja que aquesta encara no ha acabat. En canvi, lo de la resposta SDK, després de fer varies proves, observo que si printo tot el return, retorna com un "JSON" ón l'apartat ITEM és la tupla, en canvi, si retorno tant sols "response.Item", ja si que solament retorna la tupla. És això?

response.Item

**Comment by jsapes** [comment]
Correcte. Amb que tinguis en compte això es suficient. Es simplement entendre i treballar amb la sdk de un tercer.
