### ISSUE TITLE
Add a return type as a good practice

### ISSUE THREAD

**Issue by JordiSapesPlanas** [Oscars35/AWS-Practices#2]
https://github.com/Oscars35/AWS-Practices/blob/9d7e57bbd69187410d148d66099f02a6c23846e0/practices/practice2/delete.ts#L4

EL typescript permet posar el tipus de variable que retornes. Es una bona practica posar-ho sempre. De cara a futures practiques tingues en compte que utilitzarem un linter y et forçara a posar-ho.

**Comment by Oscars35** [comment]
Perfecte, ho tindré en compte de ficar-ho sempre.
Gràcies.
